clear;clc;
A = readmatrix('mobike_bike_list.csv');
figure();
histogram(A(:,1));
xlabel('出行时间/s')
ylabel('出现频数')
title('出行时间的直方图')
figure();
histogram(A(:,2));
xlabel('出行距离/m')
ylabel('出现频数')
title('距离的直方图')
figure();
histogram(A(:,3));
xlabel('速度/km/h')
ylabel('出现频数')
title('速度的直方图')
figure();
histogram(A(:,1),'BinLimits',[0,5000]);
xlabel('出行时间/s')
ylabel('出现频数')
title('出行时间的直方图')
figure();
histogram(A(:,2),'BinLimits',[0,20000]);
xlabel('出行距离/m')
ylabel('出现频数')
title('距离的直方图')
figure();
histogram(A(:,3),'BinLimits',[0,50]);
xlabel('速度/km/h')
ylabel('出现频数')
title('速度的直方图')